#!/usr/bin/env node
/**
 * AI Content Generator for FFRecipe
 * 
 * This script generates insurance articles using AI (Claude/GPT-4)
 * and saves them as MDX files in the content directory.
 * 
 * Usage:
 *   node scripts/generate-content.js --category life-insurance --topic "term life insurance basics"
 *   node scripts/generate-content.js --batch topics.json
 */

const fs = require('fs');
const path = require('path');

// Content directories
const CONTENT_DIR = path.join(__dirname, '../content');

// Article template
function generateArticleFrontMatter(options) {
  const { title, slug, description, category, author, tags, featured } = options;
  const now = new Date().toISOString();
  
  return `---
title: "${title}"
slug: "${slug}"
description: "${description}"
category: "${category}"
author: "${author || 'FFRecipe Team'}"
date: "${now}"
lastModified: "${now}"
tags: ${JSON.stringify(tags || [])}
featured: ${featured || false}
---

`;
}

// Topic templates for each category
const TOPIC_TEMPLATES = {
  'life-insurance': [
    { title: 'What is Term Life Insurance? A Complete Guide', keywords: ['term life', 'life insurance basics', 'coverage'] },
    { title: 'Whole Life vs Term Life: Which is Right for You?', keywords: ['whole life', 'term life', 'comparison'] },
    { title: 'How Much Life Insurance Do You Need?', keywords: ['coverage amount', 'life insurance calculator'] },
    { title: 'Best Life Insurance Companies of 2024', keywords: ['life insurance companies', 'rankings', 'reviews'] },
    { title: 'Life Insurance for Seniors: What You Need to Know', keywords: ['senior life insurance', 'over 50', 'guaranteed issue'] },
  ],
  'health-insurance': [
    { title: 'Understanding Health Insurance Deductibles', keywords: ['deductible', 'health insurance basics'] },
    { title: 'HMO vs PPO: Which Plan is Better?', keywords: ['HMO', 'PPO', 'health plan comparison'] },
    { title: 'Medicare Explained: Parts A, B, C, and D', keywords: ['medicare', 'medicare parts', 'senior health'] },
    { title: 'How to Choose the Right Health Insurance Plan', keywords: ['health insurance guide', 'choosing coverage'] },
    { title: 'ACA Marketplace: A Complete Guide', keywords: ['ACA', 'Obamacare', 'healthcare marketplace'] },
  ],
  'auto-insurance': [
    { title: 'Full Coverage vs Liability: What\'s the Difference?', keywords: ['full coverage', 'liability', 'auto insurance'] },
    { title: 'How to Get Cheap Car Insurance', keywords: ['cheap car insurance', 'discounts', 'savings'] },
    { title: 'Best Auto Insurance Companies of 2024', keywords: ['car insurance companies', 'rankings', 'reviews'] },
    { title: 'Understanding Car Insurance Deductibles', keywords: ['deductible', 'auto insurance basics'] },
    { title: 'SR-22 Insurance: What You Need to Know', keywords: ['SR-22', 'high risk insurance', 'DUI insurance'] },
  ],
  'home-insurance': [
    { title: 'What Does Homeowners Insurance Cover?', keywords: ['homeowners coverage', 'what\'s covered'] },
    { title: 'How to Save on Home Insurance', keywords: ['home insurance discounts', 'savings tips'] },
    { title: 'Best Home Insurance Companies of 2024', keywords: ['home insurance companies', 'rankings', 'reviews'] },
    { title: 'Renters Insurance: Why You Need It', keywords: ['renters insurance', 'tenant coverage'] },
    { title: 'Flood Insurance: Do You Need It?', keywords: ['flood insurance', 'natural disaster coverage'] },
  ],
  'guides': [
    { title: 'First-Time Insurance Buyer\'s Guide', keywords: ['insurance basics', 'first time buyer'] },
    { title: 'How to File an Insurance Claim', keywords: ['insurance claim', 'claims process'] },
    { title: 'Insurance Glossary: Key Terms Explained', keywords: ['insurance terms', 'glossary', 'definitions'] },
    { title: 'When to Shop for New Insurance', keywords: ['insurance shopping', 'switching insurers'] },
    { title: 'Understanding Insurance Premiums', keywords: ['premiums', 'insurance costs', 'pricing'] },
  ],
};

// Generate slug from title
function slugify(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

// Generate a sample article (you would replace this with actual AI generation)
function generateSampleArticle(topic, category) {
  const slug = slugify(topic.title);
  
  const frontMatter = generateArticleFrontMatter({
    title: topic.title,
    slug: slug,
    description: `A comprehensive guide about ${topic.keywords.join(', ')}.`,
    category: category,
    tags: topic.keywords,
    featured: false,
  });
  
  // Sample content - in production, this would be generated by AI
  const content = `# ${topic.title}

This is a placeholder article about ${topic.title}. In production, this content would be generated by AI (Claude or GPT-4) with comprehensive, SEO-optimized content.

## Introduction

Lorem ipsum dolor sit amet, consectetur adipiscing elit. This article covers everything you need to know about ${topic.keywords.join(' and ')}.

## Key Points

1. First important point about ${topic.keywords[0]}
2. Second key consideration
3. Third important aspect to understand

## What You Need to Know

Understanding ${topic.title.toLowerCase()} is essential for making informed insurance decisions. Here are the key factors to consider:

- **Factor 1**: Explanation of the first important factor
- **Factor 2**: Details about the second consideration
- **Factor 3**: What you should know about the third aspect

## Conclusion

Making the right choice about your insurance coverage can save you money and provide peace of mind. Always compare options and consult with licensed professionals.

---

*Need help finding the right insurance? Check out our [comprehensive guides](/guides) for more information.*
`;

  return frontMatter + content;
}

// Main function
function main() {
  const args = process.argv.slice(2);
  const categoryIndex = args.indexOf('--category');
  const topicIndex = args.indexOf('--topic');
  const batchIndex = args.indexOf('--batch');
  const allIndex = args.indexOf('--all');

  // Generate all topics
  if (allIndex !== -1) {
    console.log('Generating sample articles for all categories...\n');
    
    Object.entries(TOPIC_TEMPLATES).forEach(([category, topics]) => {
      const categoryDir = path.join(CONTENT_DIR, category);
      
      if (!fs.existsSync(categoryDir)) {
        fs.mkdirSync(categoryDir, { recursive: true });
      }
      
      topics.forEach(topic => {
        const article = generateSampleArticle(topic, category);
        const filePath = path.join(categoryDir, `${slugify(topic.title)}.mdx`);
        
        fs.writeFileSync(filePath, article);
        console.log(`Created: ${filePath}`);
      });
    });
    
    console.log('\n✅ All sample articles generated!');
    return;
  }

  // Generate single article
  if (categoryIndex !== -1 && topicIndex !== -1) {
    const category = args[categoryIndex + 1];
    const topicTitle = args[topicIndex + 1];
    
    const article = generateSampleArticle({ title: topicTitle, keywords: [category] }, category);
    const categoryDir = path.join(CONTENT_DIR, category);
    
    if (!fs.existsSync(categoryDir)) {
      fs.mkdirSync(categoryDir, { recursive: true });
    }
    
    const filePath = path.join(categoryDir, `${slugify(topicTitle)}.mdx`);
    fs.writeFileSync(filePath, article);
    
    console.log(`✅ Created: ${filePath}`);
    return;
  }

  // Show usage
  console.log(`
Usage:
  node scripts/generate-content.js --all                    Generate all sample articles
  node scripts/generate-content.js --category <cat> --topic "<title>"   Generate single article

Examples:
  node scripts/generate-content.js --all
  node scripts/generate-content.js --category life-insurance --topic "How to Buy Life Insurance"
`);
}

main();
